backend:
  name: git-gateway
  branch: main

media_folder: "img" # Onde as fotos das casas serão salvas
public_folder: "/img"

collections:
  - name: "obras"
    label: "Obras em Andamento"
    folder: "content/obras" # Pasta onde as obras serão salvas
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome da Obra", name: "title", widget: "string"}
      - {label: "Cidade/Estado", name: "local", widget: "string", default: "Crato – Ceará"}
      - {label: "Foto da Obra", name: "image", widget: "image"}
      - {label: "Etapa Atual", name: "etapa", widget: "select", options: ["Estrutura", "Acabamento", "Fundação", "Alvenaria"]}
      - {label: "Previsão de Conclusão", name: "previsao", widget: "string", hint: "Ex: Junho 2026"}
